### ISSUE TITLE
[BUG] view mode and zoom buttons

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#10]
The view mode and zoom buttons are lost below the default Windows buttons (minimize, maximize, and close).

OS: Windows 10
Penpot-Desktop Version: 0.0.5

**Comment by KorbsStudio** [comment]
Yeah, I can easily fix this later. Thanks for letting me know.

**Comment by KorbsStudio** [comment]
This is being fixed in `v0.0.6`, in development.

**Comment by Ahmadhosseinbor** [comment]
@KorbsStudio ![20220920_085835.jpg](https://user-images.githubusercontent.com/44550501/191167853-c7b9577e-c0e3-46bf-90da-cf312911df92.jpg)
