### ISSUE TITLE
Bug: Language Selection

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#12]
The current language is not shown
![Screenshot (6)](https://user-images.githubusercontent.com/44550501/191171289-3a57ac6b-ad8a-4ee6-9176-89bd9acfcd05.png)

**Comment by KorbsStudio** [comment]
Changing the language settings does work and function fine, as for it showing white text on a white background, that can easily be fixed. 

https://user-images.githubusercontent.com/51213244/191179357-d3aef123-3e5c-43af-8313-bed1b0e79cb7.mp4

**Comment by KorbsStudio** [comment]
Fixed in `v0.0.7`, should be out later tonight or tomorrow.

![image](https://user-images.githubusercontent.com/51213244/191393443-093caad8-5f3d-4dfb-a4ad-4a384268f43a.png)
