### ISSUE TITLE
MacOS : Hard move window

### ISSUE THREAD

**Issue by fantomac** [KorbsStudio/Penpot-Desktop#13]
Hi,
It's hard to move the window, especially when window is focused.
In this case, I found that you have to place the mouse as if you want to resize and the move left or right.

Otherwise, you have to leave focus, then directly click on top of the window while dragging...

https://user-images.githubusercontent.com/24393913/191192821-bae99890-ff97-4b53-8377-3da9a3097290.mp4

Little overlapping problem on the top left : 
![top left](https://user-images.githubusercontent.com/24393913/191191873-85dade9f-cb9f-4701-91b7-01b490d769c6.png)

Thanks for your work,
Have a nice day.

**Comment by KorbsStudio** [comment]
At least I know the overlay is working, but in `v0.0.6` a blank area at the top should of appear and moving the WebView down a bit.

Hmm, I really need to get a Mac ;-;

**Comment by KorbsStudio** [comment]
You are using `v0.0.6`?

**Comment by fantomac** [comment]
Yes 😅, 
0.0.6 Alpha.

**Comment by KorbsStudio** [comment]
Alright I'll attempt to look again when I wake up.

**Comment by fantomac** [comment]
Sorry 😇.
Perhaps a lot of people will use your desktop version, because of Abobe and Figma...
Penpot is now speed enough (on chrome, not yet in safari) to be usable...

**Comment by KorbsStudio** [comment]
Yeah it's great timing

**Comment by KorbsStudio** [comment]
To fix this, I just added a drag button next to the traffic light buttons.
It should work.

**Comment by fantomac** [comment]
Hi, thanks.
Just 2 littles things.

The app open in the center of the screen then go into full screen.
When trying to resize down (green light), it enter in real full screen (with no menu bar at the top)...
It requires resizing manually.

The drag button is on the right, and with a strange behavior 😅 : 
(the new project button is overlapped).

https://user-images.githubusercontent.com/24393913/191426508-38e62fee-b63c-4e5d-a528-bc744e1c5dd4.mp4

Have a nice day !

**Comment by KorbsStudio** [comment]
> The drag button is on the right, and with a strange behavior
Strange, it's acting like it's on Windows.

Also I don't have a Mac, it's very hard to support macOS right now.

**Comment by fantomac** [comment]
Comment line 57 in Penpot-Desktop-main/src/process/index.js

![code](https://user-images.githubusercontent.com/24393913/191442237-ea8fa92b-b42b-4f1c-962d-d86459b91188.png)

**Comment by KorbsStudio** [comment]
For macOS, I can prevent maximize and set this for Windows and Linux only.

**Comment by KorbsStudio** [comment]
May have to go into plan B, use native frame of the OS until I add the tabs. 😞 the overlays look sexy tho

May add overlay back when I add tabs feature.

**Comment by fantomac** [comment]
Ok

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/191455486-746d4539-8952-4a1a-95fc-0000ba4d3b34.png)
Will miss this for a while, anyways.
I guess I should start exploring the tabs feature now: #11

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/191457250-a8c80c3b-d61b-43ff-ace9-dbc8b12731c5.png)
or 🤔 maybe

**Comment by fantomac** [comment]
I try...

**Comment by KorbsStudio** [comment]
Uh, `isMac()` is not a function is current version. Something I'm trying, comparing with Windows and Linux since I have access to those operating systems.
Getting a decent VM of macOS is hard.

**Comment by fantomac** [comment]
I just saw 🤣

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/191461007-c037f66b-855e-4657-aad7-bf94ca0ae71b.png)

Yeah adding functions now in `v0.0.71`.
My console logs are pretty good.

**Comment by fantomac** [comment]
For the maximized window on MacOS.
![code](https://user-images.githubusercontent.com/24393913/191461621-4e435590-d569-49ad-97da-83aa9ac70239.png)

**Comment by KorbsStudio** [comment]
Just pushed an update, if you know how, try building it and see if it works.

Building it simple, just make sure you have NodeJS and Python installed.

**Comment by fantomac** [comment]
It's ok, no more window maximized 👍

**Comment by KorbsStudio** [comment]
What about the overlay? Is the drag button in the right spot?

**Comment by KorbsStudio** [comment]
If so, show me

**Comment by fantomac** [comment]
Same...
https://user-images.githubusercontent.com/24393913/191465184-ab2eef88-110d-41d8-b6ca-d56f72bc6d9b.mov

**Comment by KorbsStudio** [comment]
...and I don't have a mac to fix/test it.
This is really hard to fix without a mac.

**Comment by fantomac** [comment]
I know...
If I have some time I'll look if I can help.

**Comment by KorbsStudio** [comment]
I noticed the "New Project" button is off a bit. It should do that ONLY on Windows.
Why is it thinking you're on Windows? This is so weird.

**Comment by fantomac** [comment]
Little css seems to work...
![css](https://user-images.githubusercontent.com/24393913/191466539-cfd98945-30ee-495f-8670-eb6017b91db4.png)

**Comment by KorbsStudio** [comment]
No, the script I have would set `left: 73px` to `button#drag-me` if it detects you're using macOS.

**Comment by KorbsStudio** [comment]
Oh, I see, I forgot to make it `left` for macOS. That is big typo

**Comment by KorbsStudio** [comment]
Yeah, on line 11 there, change `right` to `left` and try again 😬

**Comment by fantomac** [comment]
I rebuild, but no more traffic lights. A little more margin left...
![new](https://user-images.githubusercontent.com/24393913/191470469-905d29bf-1a45-47d2-bc3a-e33a86861c3b.png)

**Comment by fantomac** [comment]
350px seems good...
![350](https://user-images.githubusercontent.com/24393913/191471404-9b8da15a-6e19-4888-bd78-01afa42d29c2.png)

**Comment by KorbsStudio** [comment]
> I rebuild, but no more traffic lights. A little more margin left... ![new](https://user-images.githubusercontent.com/24393913/191470469-905d29bf-1a45-47d2-bc3a-e33a86861c3b.png)

Easy fix, I know what I did that cause no buttons.

**Comment by KorbsStudio** [comment]
Yeah, in the webview, CSS is injected and suppose to move Projects down under the traffic lights if macOS is detected.
However, it detects your system as Windows for some odd reason.

In the console, @fantomac, run: `penpotEmbed.openDevTools()` and you should start inspecting the actual site.

The class name better be `Mac` for `<html>`.

**Comment by fantomac** [comment]
I have to go for the moment. I ‘like look when back 👍

**Comment by KorbsStudio** [comment]
Yeah, I really need to head to bed. I'll check back here in the afternoon.

**Comment by KorbsStudio** [comment]
Hey there @fantomac, checking back, is everything working as it's suppose to in the latest version? (`v0.0.8`).

**Comment by KorbsStudio** [comment]
Just contacted another Mac user, looks like traffic light buttons are broken and don't appear.

At least the drag button works.

Screenshot sent by user:
![image](https://user-images.githubusercontent.com/51213244/192077656-644903dd-a607-4cdc-b284-403126cb28b0.png)

**Comment by KorbsStudio** [comment]
With the introduction of tabs added to Penpot Desktop, fighting with CSS in the WebView won't be necessary anymore and will use the full tab bar now to drag the window.

However, I will create a patch update soon, as I forgot to move the tabs over so that the traffic light buttons don't overlay the first tab and I need to fix the full-screen thing again.

**Comment by KorbsStudio** [comment]
This should be all fixed now!

**Comment by fantomac** [comment]
Yes, very good job, everything ok 👍
A little, little little things to be perfect is to match the theme with the traffic lights bkg...

![bkgpp](https://user-images.githubusercontent.com/24393913/192277677-af364960-de29-4f77-a737-b20380b17517.png)

**Comment by KorbsStudio** [comment]
Patch update coming soon for this
