### ISSUE TITLE
Feature request: Add light mode

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#15]
An option to switch between dark and light mode and follow the system theme

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/191477306-193d0edd-11c0-4f9b-88a6-07a20c7c8b7b.png)
But I will suffer adding such a feature, do you really *need* light mode?

**Comment by KorbsStudio** [comment]
Added for `v0.0.8`

https://user-images.githubusercontent.com/51213244/191877066-66dcfeab-17f5-4ba7-9a65-685600317883.mp4
