### ISSUE TITLE
Bug: Fonts section

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#17]
In the fonts section, the background color and font are white
![Screenshot (8)](https://user-images.githubusercontent.com/44550501/191488723-3a1df81f-4e4f-41ff-b9c6-56f65d1364c2.png)

**Comment by KorbsStudio** [comment]
I thought I already I fixed this: https://github.com/KorbsStudio/Penpot-Desktop/blob/main/src/base/js/webview-dev.js#L187-L204

**Comment by KorbsStudio** [comment]
😬 So I forgot to add `!important` to some other stuff to override the CSS code.
