### ISSUE TITLE
window just disapear on windows version

### ISSUE THREAD

**Issue by brigazvi** [KorbsStudio/Penpot-Desktop#2]
https://user-images.githubusercontent.com/37640970/190900822-1b24603c-4615-4e9e-b5c6-ef89a7b0f87e.mp4

**Comment by KorbsStudio** [comment]
Yeah hostname is not set, press `ctrl` + `.` and add "https://design.penpot.app/" and click save. Then reload/restart.

**Comment by KorbsStudio** [comment]
Issued moved to #3
