### ISSUE TITLE
BUG: Open file in a new tab

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#21]
Opening the file in a new tab does not work

![Screenshot (9)](https://user-images.githubusercontent.com/44550501/192189317-dd295b87-40ff-42a5-b0bb-5c38e080bda4.png)

**Comment by KorbsStudio** [comment]
This should work 🤔 
Checking now...

**Comment by KorbsStudio** [comment]
Confirmed working. Make sure you're using the latest version `v0.0.91`

https://user-images.githubusercontent.com/51213244/192197375-504bfb84-0d61-4c30-adfd-ecc36e3b4889.mp4
