### ISSUE TITLE
Feature Request: Add Menu

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#23]
![Board12](https://user-images.githubusercontent.com/44550501/192258517-7e605f3c-98a9-4929-ad16-b7cf8c35ded8.jpg)

**Comment by KorbsStudio** [comment]
I would like to note, if you're looking for the settings, just press `ctrl` `.`.

**Comment by KorbsStudio** [comment]
In progress 

https://user-images.githubusercontent.com/51213244/193441775-9ae346cc-278c-4f84-8147-8983a0ddab2f.mp4
