### ISSUE TITLE
Feature Request: Login from Web Browser

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#5]
It would be better to login with Google like Figma

**Comment by KorbsStudio** [comment]
Hi there, Penpot's official server does support Google Auth.

Is Google blocking the app from allowing Google signins?

**Comment by KorbsStudio** [comment]
Just did a quick test, Google login seems to be working fine on my end in v0.0.5.

**Comment by Ahmadhosseinbor** [comment]
I mean the opening of the login page in the Chrome browser, I logged in to my Google account in the Chrome browser, but Penpot-Desktop wants me to log in again.

**Comment by KorbsStudio** [comment]
Yeah, uhm, not really sure how I can do this and making a web browser communicate with Penpot Desktop.
Plus, `shell.openExternal` never works for me.

**Comment by KorbsStudio** [comment]
This is going to be a bit too complicated for me.
