### ISSUE TITLE
Improve UX/UI in Login Area

### ISSUE THREAD

**Issue by timotheegoguely** [KorbsStudio/Penpot-Desktop#8]
Hi, 

Congratulations for all the work you already did on this Penpot Desktop app! 

I just downoladed the macOS version (I'm on macOS 10.15.7) to test it, and the first thing I noticed during the login step is the **weird inputs texts position** (not vertically centered, see screenshot bellow). 

The second one was to **impossibility to paste my password from my clipboard in the password field**, I needed to type it by hand.

![image](https://user-images.githubusercontent.com/8271134/190983674-4b880197-515a-458b-afa8-a343021a2bc9.png)

The login process being part of the very first impressions one has of an app, I think that fixing these 2 small details would improve a lot the onboarding experience for all future users.

Keep up the good work :)

**Comment by KorbsStudio** [comment]
Yeah, I noticed that when you sign up, there are other screens I need to theme and fix up. 
As for those inputs, I can fix this with padding.

**Comment by KorbsStudio** [comment]
Being fixed in `v0.0.6`, in development.
Preview: 
![image](https://user-images.githubusercontent.com/51213244/191093999-c061df3f-54ed-468b-b253-c07f1930852f.png)
