### ISSUE TITLE
Bug: Window Dragging not working on Windows and macOS

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#9]
Maximize button not work in windows 10

Window Dragging not work

**Comment by KorbsStudio** [comment]
Ah, it's window dragging I forgot. 
Sorry, I do all development from Linux, where the native frame is used.

I'll fix dragging later today. As for the maximize button, the app uses the native buttons from your OS, so I can't fix that.

**Comment by KorbsStudio** [comment]
This is being fixed in `v0.0.6`, in development.
